package ts3

// CHANNEL CODECS VALUES
const CODEC_SPEEX_NARROWBAND = 0x00
const CODEC_SPEEX_WIDEBAND = 0x01
const CODEC_SPEEX_ULTRAWIDEBAND = 0x02
const CODEC_CELT_MONO = 0x03
const CODEC_OPUS_VOICE = 0x04
const CODEC_OPUS_MUSIC = 0x05

// TEAMSPEAK 3 TARGET
const TARGET_CLIENT = 0x01
const TARGET_CHANNEL = 0x02
const TARGET_SERVER = 0x03

// TEAMSPEAK 3 LOG LEVEL
const LOGLEVEL_ERROR = 0x01
const LOGLEVEL_WARNING = 0x02
const LOGLEVEL_DEBUG = 0x03
const LOGLEVEL_INFO = 0x04
